const actionConstants = {
    SEARCH_CITIES_TEXT: "SEARCH_CITIES_TEXT",
    FILTERED_CITIES_RESULTS: "FILTERED_CITIES_RESULTS",
    DISPLAY_CITIES_AUTO_SUGGESTS: "DISPLAY_CITIES_AUTO_SUGGESTS",
    SEARCH_BOOKS_TEXT: "SEARCH_BOOKS_TEXT",
    FILTERED_BOOKS_RESULTS: "FILTERED_BOOKS_RESULTS",
    DISPLAY_BOOKS_AUTO_SUGGESTS: "DISPLAY_BOOKS_AUTO_SUGGESTS"
}

export default actionConstants;
